#127: Added modal functionality to insert comment to audit logs when un/locking account.
ltb-project/service-desk pull request #140
Opened 2024-07-18 14:59 UTC by abpai94

#127

2024-07-19 15:58 UTC, coudot requested changes
Please look at suggestions.

And configuration parameters are missing for now.

2024-07-19 15:58 UTC, coudot commented on docs/audit.rst
>      "result":"accountlocked"
A comma is missing here

2024-07-19 15:58 UTC, coudot commented on docs/audit.rst
>      "result":"accountlocked"
```suggestion
    "result":"accountlocked",
```

2024-07-19 15:58 UTC, coudot commented on htdocs/lockaccount.php
> +$comment = $_POST["comment"];
Like other POST params, you should check the presence of the param with isset (see example with "dn" just below)

2024-07-19 15:58 UTC, coudot commented on lang/en.inc.php
> +$messages['label_comment'] = "Comment";
label_x is reserved to tranlsation of LDAP attributes, another key like "comment" and rename "comment" key to "insert_comment"

2024-07-22 09:24 UTC, coudot approved these changes

2024-07-22 09:33 UTC, coudot commented
Hello @abpai94 

thanks for the modifications, all is working fine!

Before merging it, I think we should:
* Add missing translation string (I can do it)
* Decide if we want to change the color of the button if a comment is expected (I don't think it is needed)
* I would suggest to change the modal header title to the action (Unlock, Lock, ...) so the admin knows which action is concerned by the comment
* Do not store the comment key in audit if comment is empty
* See if the comment should be mandatory. Maybe we could add another parameter to manage this.

2024-07-22 15:11 UTC, abpai94 commented
Hello @coudot 

The following three points have been covered:

> - [x] I would suggest to change the modal header title to the action (Unlock, Lock, ...) so the admin knows which action is concerned by the comment 
> - [x] Do not store the comment key in audit if comment is empty 
> - [x] See if the comment should be mandatory. Maybe we could add another parameter to manage this.

2024-07-23 08:35 UTC, merged

2024-08-21 16:54 UTC, coudot commented
Regression found:
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function auditlog(), 5 passed in /usr/local/service-desk/htdocs/checkpassword.php on line 44 and exactly 6 expected in /usr/local/service-desk/lib/audit.inc.php:2\nStack trace:\n#0 /usr/local/service-desk/htdocs/checkpassword.php(44): auditlog()\n#1 /usr/local/service-desk/htdocs/index.php(202): require_once('...')\n#2 {main}\n  thrown in /usr/local/service-desk/lib/audit.inc.php on line 2'
```

Will fix it in master